name: build
on:
  release:
    types: [published]
  # push:
  # pull_request:
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: "npm"

      - name: Install Dependencies
        run: npm install --include=dev && npm install -g vsce

      - name: VSCE Build Package Release
        if: github.event_name == 'release' && github.event.release.prerelease == false
        run: vsce package -o vscode-cython.vsix

      - name: VSCE Build Package Pre-Release
        if: github.event_name == 'release' && github.event.release.prerelease != false
        run: vsce package -o vscode-cython.vsix --pre-release

      - name: Upload Artifact
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: vscode-cython.vsix

      - name: Test
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release'
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload Release Artifact
        run: gh release upload ${{ github.ref_name }} dist/vscode-cython.vsix -R ${{ github.repository }} --clobber

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: "npm"

      - name: Install VSCE
        run: npm install -g vsce

      - name: Publish Release
        if: github.event.release.prerelease == false
        run: vsce publish -i dist/vscode-cython.vsix -p ${{ secrets.TOKEN }}

      - name: Publish Pre-Release
        if: github.event.release.prerelease == true
        run: vsce publish -i dist/vscode-cython.vsix -p ${{ secrets.TOKEN }} --pre-release
